### ISSUE TITLE
icons are not in same dimension!

### ISSUE THREAD

**Issue by NinaPacifier** [blender/docs.blender.org#11]
![blenderorg1](https://user-images.githubusercontent.com/68914076/102023077-fcd09a80-3db0-11eb-8b2c-e24864f97688.png)
### **Facebook icon in the footer section is small in dimension comparing the icons of Youtube, Twitter, and Instagram.**

**Comment by NinaPacifier** [comment]
@mcgrathd If you allow then I want to work on this issue.

**Comment by mcgrathd** [comment]
Hi Nina,

Well, it's not me call, per se, but I don't see why anyone would object to a PR that improved things!

I see go for it. We can certainly do a merge and put it live if nobody objects.

**Comment by NinaPacifier** [comment]
@mcgrathd  Created the PR of this issue, waiting for its review.
https://github.com/blender/docs.blender.org/pulls

**Comment by nyctonio** [comment]
@mcgrathd  can i work on this issue

**Comment by mcgrathd** [comment]
It would probably be better if you mailed the docboard mailing list for this, or join the [Blender Chat docs](https://blender.chat/channel/docs) channel.

Try subscribe to the mailing list, visit: https://lists.blender.org/mailman/listinfo/bf-docboard

**Comment by mcgrathd** [comment]
Any progress on this?

**Comment by mcgrathd** [comment]
@Blendify asked for this to be closed as it is no longer an issue.
