### ISSUE TITLE
Add  a Hover Effect !

### ISSUE THREAD

**Issue by pratiksrivastava01** [blender/docs.blender.org#18]
Hi, there This is Pratik Srivastava and I want to add a hover effect to the landing page of the blender website and make the UI look more good-looking would create a good user experience
![Blender ](https://user-images.githubusercontent.com/92784294/156371228-10877ed7-01f3-4c19-8d4d-4215761b1306.png)

**Comment by Sugarlust** [comment]
I think I can contribute to this can you please tell me where the hover effect should be?

**Comment by mcgrathd** [comment]
Try get hold of Pablo Vazquez in the #blender-coders channel over on [blender.chat](https://blender.chat/channel/blender-coders). He would probably be a good person to pass ideas by for the look and feel of the site.

Thanks!

**Comment by mirkan1** [comment]
I think this repository is unrelieved with the actual docs, it redirects me to [original website](https://docs.blender.org) when I clicked getInvolve button so I cant work on it on localhost

**Comment by mcgrathd** [comment]
> also, chrome doesn't even let me download this repository claiming that it has a virus, It is claiming that footer.html is containing a virus, when I try to open it on an IDE it directly deletes it

That's not a virus, that's just a Faceb**k URL ;)

Scans from Bit Defender found nothing wrong with the file. Perhaps your computer is infecting files?

**Comment by mcgrathd** [comment]
A WinRAR scan of the ZIP from FireFox (which lets me download), shows similar "virus", when I use Windows Defender as well, yet the cloned repo doesn't show it. This may be a problem only with the ZIP file from GitHub.

@mirkan1 Any chance you could try a GitHub desktop clone/checkout and scan the files manually?

**Comment by mirkan1** [comment]
I was able to download it using firefox as well, but like I said this issue is related to the getInvolved > Development page which does not exist in this repository, I think the owner can close this issue since it is irrelevant

**Comment by mcgrathd** [comment]
> I was able to download it using firefox as well, but like I said this issue is related to the getInvolved > Development page which does not exist in this repository, I think the owner can close this issue since it is irrelevant

Try open up another issue specifically for this. Thanks!

**Comment by venomgfx** [comment]
Could you describe what's your intention with this issue? What are you trying to achieve?

**Comment by venomgfx** [comment]
Closing this due to lack of response. The site has changed a lot since March anyway so perhaps it's no longer needed.
