### ISSUE TITLE
press f12 and blender crash

### ISSUE THREAD

**Issue by Xoirad** [blender/docs.blender.org#22]
[blender_system_info.txt](https://github.com/blender/docs.blender.org/files/10421363/blender_system_info.txt)
[blender_debug_output.txt](https://github.com/blender/docs.blender.org/files/10421364/blender_debug_output.txt)

**Comment by Xoirad** [comment]
help me !

**Comment by mcgrathd** [comment]
Hi Xoirad. Unfortunately this repository is for documentation, not Blender.

Please use developer.blender.org to report bugs in blender.

Thanks!
